In [1]:
import numpy as np

In [2]:
a = np.array([[1,2],[3, 4] ])
a.ndim

2

In [3]:
a.itemsize

8

In [4]:
a.dtype

dtype('int64')

In [9]:
b = np.array([[1,2],[3, 4], [5, 6] ], dtype=np.int16)
b.dtype

dtype('int16')

In [7]:
b.size

4

In [10]:
b.shape

(3, 2)

In [17]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [25]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [26]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [27]:
a.shape

(2, 2)

In [34]:
a.reshape(1, 4)

array([[1, 2, 3, 4]])

In [36]:
c = a.ravel()
c

array([1, 2, 3, 4])

In [37]:
a.min()

1

In [38]:
a.max()

4

In [39]:
a.sum()

10

In [42]:
a

array([[1, 2],
       [3, 4]])

In [43]:
a.sum(axis=0)

array([4, 6])

In [44]:
a.sum(axis=1)

array([3, 7])

In [45]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [46]:
np.std(a)

1.118033988749895

In [47]:
a

array([[1, 2],
       [3, 4]])

In [48]:
b

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int16)

In [53]:
d = np.array([[10, 20], [30, 40]])

In [54]:
d

array([[10, 20],
       [30, 40]])

In [55]:
a+d

array([[11, 22],
       [33, 44]])

In [57]:
a.dot(d)

array([[ 70, 100],
       [150, 220]])

In [58]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr[0:4]

array([1, 2, 3, 4])

In [61]:
arr[-1]

9

In [63]:
m_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
m_arr[1,2]

6

In [69]:
m_arr[0:3, 2]

array([3, 6, 9])

In [70]:
m_arr[-1]

array([7, 8, 9])

In [73]:
m_arr[-1, 0:1]

array([7])

In [74]:
for row in m_arr:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [75]:
for cell in m_arr.flat:
    print(cell)

1
2
3
4
5
6
7
8
9


In [76]:
arr1 = np.arange(6).reshape(3, 2)
arr2 = np.arange(6, 12).reshape(3, 2)
arr2

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [77]:
np.vstack((arr1, arr2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [78]:
np.hstack((arr1, arr2))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [80]:
arr3 = np.arange(30).reshape(2, 15)
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [82]:
np.hsplit(arr3, 3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [84]:
np.vsplit(arr3, 2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [85]:
arr4 = np.arange(12).reshape(3, 4)
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
bol = arr4> 4
bol

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [89]:
arr4[bol]

array([ 5,  6,  7,  8,  9, 10, 11])

In [92]:
arr4[bol] = -1
arr4

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [93]:
arr5 = np.arange(12).reshape(3, 4)
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
for row in arr5:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [95]:
for row in arr5:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [96]:
for cell in arr5.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [97]:
for x in np.nditer(arr4, order='c'):
    print(x)

0
1
2
3
4
-1
-1
-1
-1
-1
-1
-1


In [98]:
for x in np.nditer(arr4, order='f'):
    print(x)

0
4
-1
1
-1
-1
2
-1
-1
3
-1
-1


In [100]:
for x in np.nditer(arr4, order='f', flags=['external_loop']):
    print(x)

[ 0  4 -1]
[ 1 -1 -1]
[ 2 -1 -1]
[ 3 -1 -1]


In [101]:
for x in np.nditer(arr5, op_flags=['readwrite']):
    x[...]=x*x

In [102]:
arr5

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [103]:
arr6 = np.arange(3, 15, 4).reshape(3, 1)
arr6

array([[ 3],
       [ 7],
       [11]])